---
sudo: required
language: objective-c
# 10.13 (see https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)
osx_image: xcode9.3

install:
  # bootstrap
  - ./install

before_script:
  # https://github.com/Homebrew/homebrew-core/issues/26358
  - brew upgrade python || true
   # https://github.com/Homebrew/homebrew-core/issues/24978
  - brew uninstall --force mercurial
  - brew install mercurial
  # travis issue?
#  - brew install python@2
#  - brew install hg
#  - if (brew outdated | grep openssl > /dev/null); then brew upgrade openssl || true; fi
#  - brew missing || true
#  - brew doctor || true


script:
  - bin/macos-setup ci
  # idempotence
  #- idempotence=$(mktemp)
  #- "bin/macos-setup ci | tee -a ${idempotence}"
  #- >
  #  tail ${idempotence}
  #  | grep -q 'changed=0.*failed=0'
  #  && (echo 'Idempotence test: pass' && exit 0)
  #  || (echo 'Idempotence test: fail' && exit 1)

after_script:
  - ls -lah ~
  - ls -lah /Applications
