#!/usr/bin/env bash
echo 'Checking we can begin installation...'
echo -e "\n\n"

# is Xcode installed?
xcode-select -p &> /dev/null

if [[ $? != 0 ]]; then
    echo "Is Xcode installed correctly?"
    exit $?;
fi


install_dir="${HOME}/.macos-setup"

if [ -d $install_dir ]
then
    echo "Installation directory ${install_dir} already exists"
    exit 1
fi

echo 'Checking out macOS Setup repo...'
echo -e "\n\n"
git clone https://github.com/bennoislost/macos-setup $install_dir 2>/dev/null

echo 'Bootstrapping (will require your sudo password)...'
echo -e "\n\n"
"${install_dir}/bin/macos-setup" bootstrap
