---
- name: Create ~/.ssh/config
  template:
    src: config.j2
    dest: ~/.ssh/config
    mode: 0644

- name: Create ~/.ssh/customer-config.d directory exists
  file:
    path: "~/.ssh/customer-config.d"
    state: directory
    mode: 0700

- name: Ensure template ~/.ssh/config.local file exists
  copy:
    content: ""
    dest: "~/.ssh/config.local"
    force: no
    mode: 0644

- name: Ensure template ~/.ssh/known_hosts file exists
  copy:
    content: ""
    dest: "~/.ssh/known_hosts"
    force: no
    mode: 0644
