- name: Preference directories exist
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "~/.composer"
    - "~/.hem"
    - "~/Sites"
    - "~/Projects"
    - "~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/"
    - "~/Library/Application\ Support/Spectacle/"

- name: Create hem config
  copy:
    dest: "~/.hem/config.yaml"
    content: "{{ macos_hem_aws_properties }}"
    mode: "600"

- name: Create composer auth config
  copy:
    dest: "~/.composer/auth.json"
    content: "{{ macos_composer_github_auth }}"
    mode: "600"

- name: Create Sublime Text preferences
  template:
    src: "Benno.sublime-settings.j2"
    dest: "~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings"
    mode: 0644

- name: Create Spectacle preferences
  template:
    src: "Spectacle-Shortcuts.j2"
    dest: "~/Library/Application\ Support/Spectacle/Shortcuts.json"
    mode: 0644

- name: Create stunnel directory
  file:
    path: "/usr/local/etc/stunnel"
    state: directory
    mode: 0775

- name: Add stunnel foreground example file
  template:
    src: "Stunnel-foreground.conf-example.j2"
    dest: "/usr/local/etc/stunnel/stunnel-foreground.conf-sample"
    mode: 0644


