---
- name: Set php_executable variable to a default if not defined.
  set_fact:
    php_executable: php
  when: php_executable is not defined

- name: Check if Composer is installed.
  stat:
    path: /usr/local/bin/composer.phar
  register: composer_bin

- name: Get Composer installer signature.
  uri:
    url: https://composer.github.io/installer.sig
    return_content: true
  register: composer_installer_signature
  when: not composer_bin.stat.exists

- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not composer_bin.stat.exists

- name: Run Composer installer.
  command: >
    {{ php_executable }} composer-installer.php
  args:
    chdir: /tmp
  when: not composer_bin.stat.exists

- name: Move Composer into globally-accessible location.
  command: >
    mv /tmp/composer.phar /usr/local/bin/composer.phar
  args:
    creates: /usr/local/bin/composer.phar
  when: not composer_bin.stat.exists

- name: Ensure composer directory exists.
  file:
    path: "~/.composer"
    state: directory
    mode: 0755

- name: Add Composer auth
  template:
    src: "auth.json.j2"
    dest: "~/.composer/auth.json"
    mode: 0644
  when: composer_auth_json | length > 0

- name: Install configured globally-required packages.
  command: >
    /usr/local/bin/composer.phar global require {{ item.name }}:{{ item.release | default('@stable') }} --no-progress --no-interaction
  args:
    creates: "~/.composer/vendor/{{ item.name }}"
  environment:
    COMPOSER_HOME: "~/.composer"
  with_items:
    - name: laravel/valet
