name: CI
on:
    push:
        branches:
            - feature/gh-actions

jobs:
    build:
        runs-on: macOS-latest
        steps:
            - run: 'echo "$VAULT_SECRET" > ~/ansible_vault_secret'
              shell: bash
              env:
                VAULT_SECRET: ${{secrets.VAULT_SECRET}}
            - run: |
                cat ansible_vault_secret
            - uses: actions/checkout@v2
            - run: |
                ./install
                bin/macos-setup ci
              env:
                DEFAULT_VAULT_PASSWORD_FILE: ~/ansible_vault_secret
            - run: |
                rm -f ~/ansible_vault_secret
